# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "db441210fdaf92721bdd8a3fd4a3d554"
application_url = "https://apps.royalhawaiianheritage.com/install.php"
embedded = true
name = "RHHJ Custom Product Options "
handle = "rhhj-custom-product-options"

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_assigned_fulfillment_orders,write_assigned_fulfillment_orders,write_cart_transforms,write_checkouts,read_checkouts,read_customers,write_customers,read_customer_data_erasure,write_customer_data_erasure,read_customer_merge,read_price_rules,write_price_rules,read_discounts,write_discounts,write_draft_orders,read_draft_orders,write_inventory,read_inventory,write_locations,read_locations,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders,write_order_edits,read_order_edits,read_orders,write_orders,read_product_feeds,write_product_feeds,read_product_listings,write_product_listings,read_products,write_products,read_script_tags,write_script_tags,read_shipping,write_shipping,write_theme_code,read_themes,write_themes,read_third_party_fulfillment_orders,write_third_party_fulfillment_orders,customer_read_draft_orders,customer_read_orders,customer_write_orders,unauthenticated_write_checkouts,unauthenticated_read_checkouts,unauthenticated_read_product_pickup_locations,unauthenticated_read_product_inventory,unauthenticated_read_product_listings,unauthenticated_read_product_tags"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://apps.royalhawaiianheritage.com/callback.php" ]
